# Assignment Applied Machine Learning BSc IK 

## Notebook made by

**Gebruik graag dit formaat**

* Voor de namen:  voornaam rest van je naam, voornaam rest van je naam,....
* je studentnummers: hetzelfde: scheidt met `,`
* je emails: hetzelfde: scheidt met `,`
* voor je groep: **alleen de hoofdletter** (iets als  `A` of `B` dus)

__Namen__: 

__Emails__: 

__Student ids__ : 

__Groep__ : VervangMijDoorEenHoofdletter

## Toelichting

* Een aantal opgaven worden automatisch nagekeken. Bij vrijwel alle opdrachten staan er een paar tests onder de opdracht, dit is voornamelijk om te zorgen dat je de juiste type output geeft. Dit zijn dus *NIET* alle tests, die komen er bij het graden nog bij.
* Elke vraag is 1 punt waard, tenzij anders aangegeven. Soms is die punt onderverdeeld in deelpunten, maar niet altijd. 

## Voor het inleveren!

* Pas niet de cellen aan, vooral niet die je niet kunt editen. Dit levert problemen op bij nakijken. Twijfel je of je per ongeluk iets hebt gewijzigd, kopieer dan bij inleveren je antwoorden naar een nieuw bestand, zodat het niet fout kan gaan.

* Zorg dat de code goed runt van boven naar beneden, verifieer dat door boven in Kernel -> Restart & Run All uit te voeren

## Na het inleveren!

* Het gebeurt erg vaak dat mensen een "leeg bestand" inleveren. Vaak een andere versie van de opgave die nog ergens op je computer rondslingerde. Zonde van al je werk toch!
* Dus, lever **minstens een half uur voor tijd in**. Download dan wat je hebt ingeleverd op Canvas. Geef het een andere naam om verwarring te voorkomen. En draai alle cellen, en bekijk het. Geen syntax fouten? Alle vragen gemaakt? Dan zit het vast wel goed, en hoef je niet in de zenuwen te zitten.

# Applied Machine Learning W1
 

In [359]:
!pip install nose

In [374]:
import os
import sys

import numpy as np
import pandas as pd
import seaborn as sns

import sklearn
from scipy.stats import mode
from nose.tools import assert_count_equal, assert_equal
from numpy.testing import *
from pandas.testing import assert_frame_equal
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn import datasets
# Please do not remove this: 
np.random.seed(31415)

# Theory

With these questions you and your group will practice your ability to formulate key concepts precisely and short. 
Such questions  also appear in the exams, and are graded quite strict.

Always answer in one grammatically correct English sentence. 

Finish the following sentences:

1. Machine learning algorithms build a model ...
2. Machine learning can be divided into three parts, namely .....
3. Each of these 3 parts can be described as follows:
    1. .... is ....
    1. .... is ....
    1. .... is ....
4. The key difference between regression and classification problems is .....


1. Machine learning algorithms build a model by analyzing sample/training data to train a model , which can be used to make predictions on new unseen data without explicitly programming.
2. Machine learning can be divided into three parts, namely unsupervised learning, supervised learning and reinforcement learning.
3. Each of these 3 parts can be described as follows: 
       A. Unsupervised learning is a machine algorithm using only the input data to extract knowledge from this data
       B. Supervised learning is used to predict a certain outcome from a given input, with examples of input/output pairs.
       C. Reinforcement learning is used to find out how to handle new situations by rewarding desired behaviors and punishing undesired ones. 
4. The key difference between regression and classification problems is the data of the predicted value, which is categorical for classification problems and numerical for the regression problems.

# Part 0 classification with the iris data set, using knn

In [375]:
#https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html
iris= datasets.load_iris()

X,y= iris.data, iris.target
print(X.shape,y.shape)
print(X[:5])
print(y)

(150, 4) (150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# train test

Use `np.random.choice` to create random `X_train, X_test, y_train, y_test`  such that 

1. 90 train, 60 test
2. Stratified, so an equal amount of cases from each of the three classes in the train and test sets.

Make tests to test that what you create is according to these specs.

## Note about our questions, and how to answer them

Here and later we may ask you to program things explicitly, and thus **not** using a scikit learn or other routine. Please do so, and practice this. We will do the same in the exam. It is important that you understand the algorithms behind the concepts that you use. That is the reason. Also we believe that you understand and remember things better when you have programmed than from scratch.

Of course you can google the answer in a few minutes and copy-paste it. But does that give your satisfaction or gratification? Do you *learn* anything from it? Please do not work like that. You make these assignments with 4 students, so you really have a lot of time. Make them all, compare and discuss the 4 found solutions, improve and refactor  them to one super great siolution. And, if all this does not appeal to you, then maybe this does: at the exam we will also ask these questions, and you do not have access to the web then. 

### making tests

This is an underdeveloped skill with many students. Why? Testing your own answer gives you a good feeling, it often lets you improve your answer, and can also be seen as a way to find the (complete) answer. **Please practice it and take it seriously.** At the exam you will have a notebook too, and so you can also test your own answers. Being skillfull in testing will boost your grade.

In [376]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)


for M in [X_train, y_train, X_test,  y_test]:
    answers = [(90, 4), (90,), (60,4), (60,)]
    if M.shape in answers:
        print("good")
    else:
        print("bad")
print(y_test)

good
good
good
good
[1 1 0 1 1 0 2 1 2 0 1 0 1 1 2 2 0 0 2 1 0 2 2 1 0 0 2 0 1 1 1 1 2 2 1 2 2
 2 2 1 2 2 1 1 1 1 2 1 1 2 2 1 2 0 0 1 1 0 0 0]


In [377]:
assert_equal(X_train.shape,(90, 4))
assert_equal(X_test.shape,(60, 4))
assert_equal(y_train.shape,(90, ))
assert_equal(y_test.shape,(60, ))

# knn classifier

Program from scratch a knn classifier which can work on data `X` and `y` as you have from the iris dataset.

It returns the most common label in the k nearest neighbors.

### Hints

* use `euclidean` as your distance function
* `X_train[0,:]` picks out the first instance from `X_train`.
* Use *fancy indexing* to take out a number of items from a numpy array. as in `X[8,35,7,2]`.
* `np.argsort` is handy.

In [382]:
from scipy.stats import mode
from scipy.spatial.distance import euclidean

def knn(X,y,example,k=5):
    '''Classify example using majority vote of the k closest items in X with labels y.'''
    test = [y[i] for i in np.argsort([euclidean(example, node) for node in X])[:k]]

    return mode(test)[0][0]

[ knn(X_train,y_train,i) for i in X_test[:10]] 

 

[1, 1, 0, 1, 1, 0, 2, 1, 2, 0]

# Evaluate

Run knn on `X_test` and compare the outcomes to `y_test`.

Come up with a useful and insightfull error report.

In [384]:
test_values = [ knn(X_train, y_train, X_test[i]) == y_test[i] for i in range(len(X_test))]
test_values

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

# Make more efficient

1. Estimate what work is done when running knn on one new to be classified instance, given that it has $n$ training examples. 
2. How expensive is the sorting step?
3. Remove the sorting step by programming a heap of size $k$ which contains from the train set already inspected  the $k$ closest instances to the unseen example.

YOUR ANSWER HERE

In [234]:
def knn_heap(X,y,example,k=5):
    '''Classify example using majority vote of the k closest items in X with labels y.'''
    #WRITE YOUR CODE HERE
    return mode(kNN_Y)[0][0]


[ knn(X_train,y_train,i) for i in X_test[:10]] 

 

[0, 1, 0, 0, 2, 1, 0, 0, 1, 2]

# Predicting a value with knn-regression

## Part 1: Loading the data into a Pandas Data Frame  

The descriptions of the columns of the dataset can be found here:

**pop**: population

**pctUrban**: percentage of people living in areas classified as urban

**medIncome**: Median Income

**pct12-29**: percentage of population that is 12-21 in age

**pct65up**: percentage of population that is 65 and over in age

**pctPoverty**: percentage of people under the poverty level

**pctAllDivorc**: percentage of population who are divorced

**pctUnemploy**: percentage of people 16 and over, in the labor force, and unemployed

**perHoush**: mean persons per household

**pctHousOccup**: percent of housing occupied

**persHomeless**: number of homeless people

**persEmergShelt**: number of people in homeless shelters

**nonViolPerPop**: total number of non-violent crimes per 100K popuation

**State**: the state in which this town/city is located

**countyCode**: the code number of the county of the state this town/city is located



### Question 1a:
Load the data into a Pandas DataFrame. At this point, make sure that you only load the following columns: 

`'pop', 'pctUrban', 'medIncome', 'pct12-29', 'pct65up', 'pctPoverty', 'pctAllDivorc', 'pctUnemploy', 'perHoush', 'pctHousOccup', 'persHomeless', 'persEmergShelt', 'nonViolPerPop'`


Here and elsewhere, when we load data, always use the `loadfile()` command. Like in `pd.read_csv(loadfile())`. We do this because when we (auto)grade we have the file not in the same directory as the notebook.

In [287]:
def loadfile():
    if 'crime_data.csv.gz' in os.listdir():
        return 'crime_data.csv.gz'
    elif os.path.exists('../../data/Week1/'):
        return '../../data/Week1/crime_data.csv.gz'
    elif os.path.exists('../../../data/Week1/'):
        return '../../../data/Week1/crime_data.csv.gz'
    


In [288]:
# Load the dataset
crime_data = pd.read_csv("crime_data.csv.gz", usecols=['pop', 'pctUrban', 'medIncome', 'pct12-29', 'pct65up', 'pctPoverty', 'pctAllDivorc', 'pctUnemploy', 'perHoush', 'pctHousOccup', 'persHomeless', 'persEmergShelt', 'nonViolPerPop'])

print(crime_data.shape)
crime_data.head()

(949, 13)


perHoush  pct12-29  pct65up  pctUrban  pctPoverty  pctUnemploy  \
0      3.10     21.44    11.33     100.0        1.96         2.70   
1      2.82     21.30    17.18     100.0        3.98         2.43   
2      2.76     40.53    12.65       0.0       29.99         9.08   
3      2.60     27.41    14.42     100.0        4.01         4.85   
4      2.46     35.16     8.58     100.0       13.68         4.18   

   pctAllDivorc  pctHousOccup  persEmergShelt  persHomeless  nonViolPerPop  \
0          4.47         98.37              11             0        1394.59   
1          5.42         97.15               0             0        1955.95   
2          9.73         92.45               2             0        9988.79   
3          7.64         95.11               0             0        1890.88   
4          8.64         95.07             125            15        4747.58   

   medIncome      pop  
0    75122.0  11980.0  
1        NaN  23123.0  
2        NaN      NaN  
3    42805.0  28700.0  
4        NaN  74111.0

In [289]:
assert_equal(crime_data.shape,(949, 13))
assert_count_equal(crime_data.columns,['pop',
            'pctUrban',
            'medIncome',
            'pct12-29',
            'pct65up',
            'pctPoverty',
            'pctAllDivorc',
            'pctUnemploy',
            'perHoush',
            'pctHousOccup',
            'persHomeless',
            'persEmergShelt',
            'nonViolPerPop'
           ])

### Question 1b:
We want to predict the number of crimes. Identify the features X and the target variable Y, and turn the X and Y DataFrames into Numpy arrays.

Make sure `Y` is of shape `(949, 1)`.

In [455]:
X = np.array(crime_data)
X = np.delete(X, 10, axis=1)
Y = np.array((crime_data['nonViolPerPop'])).reshape((949, 1))



#WRITE YOUR CODE HERE
print(X.shape,Y.shape)
print(X[:3])
print(Y[:5])

(949, 12) (949, 1)
[[3.1000e+00 2.1440e+01 1.1330e+01 1.0000e+02 1.9600e+00 2.7000e+00
  4.4700e+00 9.8370e+01 1.1000e+01 0.0000e+00 7.5122e+04 1.1980e+04]
 [2.8200e+00 2.1300e+01 1.7180e+01 1.0000e+02 3.9800e+00 2.4300e+00
  5.4200e+00 9.7150e+01 0.0000e+00 0.0000e+00        nan 2.3123e+04]
 [2.7600e+00 4.0530e+01 1.2650e+01 0.0000e+00 2.9990e+01 9.0800e+00
  9.7300e+00 9.2450e+01 2.0000e+00 0.0000e+00        nan        nan]]
[[1394.59]
 [1955.95]
 [9988.79]
 [1890.88]
 [4747.58]]


In [456]:
assert isinstance(X, np.ndarray)
assert isinstance(y, np.ndarray)
assert_equal(X.shape,(949, 12))
assert_equal(Y.shape,(949, 1))

## Part 2: Split the data into a training set and a test set 
### Question 2:
Split the data into a training and a test set, using teh appropriate sklearn function. Use a  70%-30% split.  
Print the number of examples in the training set and the test set.

In [457]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)


for M in [X_train, X_test, Y_train, Y_test]:
    print(M.shape)

(664, 12)
(285, 12)
(664, 1)
(285, 1)


In [458]:
assert X_train.shape== (664, 12)
assert Y_test.shape== (285,1)


## Part 3: Knn Regression [2 pts]

In [459]:
# figure out what this means, and what does it mean when taking the sum?
crime_data.isna().sum()

perHoush           0
pct12-29           0
pct65up            0
pctUrban           0
pctPoverty         0
pctUnemploy        0
pctAllDivorc       0
pctHousOccup       0
persEmergShelt     0
persHomeless       0
nonViolPerPop      0
medIncome         95
pop               95
dtype: int64

In [460]:
np.isnan(X_test)#.sum(0)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False]])

In [452]:
np.isnan(X_test[:,0])#.sum()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

**Missing Data**: Often the data you are considering is incomplete. For example in some city, the number of homeless people might be unknown. In this case, if you look into the datasets you will find the value *NaN*. This is not a real value, hence Linear Regression cannot handle it.

The question is how can we handle missing data. There are many ways to do so, some more sophisticated than others. Here we will use a simple approach. This simple approach fills in the missing values, i.e. replaces the *NaN* by the median of the corresponding feature. E.g. if there is a *NaN* value for the population in one city, this *NaN* value will be replaced by the median number of the population in all other cities in the data.

1. figure out what this code  `np.isnan(X_test).sum(axis=0), np.isnan(X_train).sum(axis=0) `    is doing. Remove the `axis=0`, and replace it by `axis=1`. You get it?
2. What is the median of the values in the first column of `X_test`?  (variable `v2`)
    * Why does `np.median` not work ;-) You are close though! 
3. Create the first column of X_test in which you replaced all nan values by the median of the first column. (variable `v3`)
5. Then do this for all columns at once   using Scikit learn's `SimpleImputer`.
    * So the new `X_train` and `X_test` have no more missing values.
6. Check that you get exactly the same result using your own method and sklearn's.  

In [461]:
v2=np.nanmedian(X_test, axis=0)[0]
v3=np.nan_to_num(X_test, v2) # None verplaatsen met median 
 
print(v2)
print(v3[:10])
print(np.isnan(v3).sum())
# naize test
# all places in v3 which were nan in  X_test[:,0] are now equal to v2
print(v3[np.isnan(X_test[:,0])]==v2)


2.68
[[2.77000e+00 2.37700e+01 1.04100e+01 9.57500e+01 4.07000e+00 4.72000e+00
  7.18000e+00 9.70500e+01 0.00000e+00 0.00000e+00 3.49780e+04 1.07420e+04]
 [2.53000e+00 2.45900e+01 1.66000e+01 1.00000e+02 6.79000e+00 5.57000e+00
  9.67000e+00 9.58800e+01 0.00000e+00 0.00000e+00 3.10070e+04 0.00000e+00]
 [2.93000e+00 2.55900e+01 1.25100e+01 6.57600e+01 4.92000e+00 4.60000e+00
  6.44000e+00 9.60000e+01 0.00000e+00 0.00000e+00 4.01170e+04 1.54110e+04]
 [2.47000e+00 2.30100e+01 1.89600e+01 1.00000e+02 4.70000e+00 4.71000e+00
  7.93000e+00 9.68100e+01 2.00000e+00 0.00000e+00 3.99050e+04 7.17420e+04]
 [2.68000e+00 2.44100e+01 1.26300e+01 1.00000e+02 2.07000e+00 3.61000e+00
  8.65000e+00 9.71200e+01 0.00000e+00 0.00000e+00 4.88640e+04 1.05390e+04]
 [2.45000e+00 2.60600e+01 1.67900e+01 1.00000e+02 6.25000e+00 7.20000e+00
  9.63000e+00 9.44000e+01 1.80000e+01 0.00000e+00 3.58080e+04 1.21990e+04]
 [2.73000e+00 3.45200e+01 1.19100e+01 1.00000e+02 2.29600e+01 9.18000e+00
  1.13700e+01 8.81900e+01 2

In [462]:
assert isinstance(v2,np.float) 
assert np.isnan(v3).sum()==0

/var/folders/5x/kl0ttwmn26v7_2rdrw520mwc0000gn/T/ipykernel_40041/346195263.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert isinstance(v2,np.float)


In [463]:
# Fill in the missing data in the dataset (i.e. replace NaN values in both X_train and X_test) 
from sklearn.impute import SimpleImputer

X_test = np.nan_to_num(X_test, np.nanmedian(X_test, axis=0)[0])
X_train = np.nan_to_num(X_train, np.nanmedian(X_train, axis=0)[0])
#WRITE YOUR CODE HERE
print(np.isnan(X_train).sum())
print(np.isnan(X_test).sum())
print(X_test[:,0])

0
0
[2.77 2.53 2.93 2.47 2.68 2.45 2.73 2.75 2.82 2.86 2.77 2.81 2.91 2.45
 2.89 2.51 2.92 2.8  2.49 2.46 2.55 2.47 2.66 2.56 2.81 2.56 2.53 3.04
 2.53 2.65 2.53 2.57 2.67 2.72 2.77 2.72 2.84 2.88 3.07 2.36 2.43 2.43
 2.74 2.32 3.14 3.04 2.75 2.36 2.41 2.61 2.56 2.72 3.1  2.91 2.7  2.34
 2.8  2.76 3.11 2.87 2.94 2.5  2.87 2.77 2.76 2.59 2.44 2.51 2.7  2.81
 2.68 3.02 2.6  2.96 3.87 3.07 2.9  2.48 2.92 3.17 2.45 2.83 2.66 2.47
 2.99 2.62 2.67 2.46 2.42 2.58 2.67 2.54 2.87 2.53 2.65 2.69 2.95 2.81
 2.75 3.   2.63 3.06 2.8  2.63 2.94 2.38 2.94 3.28 2.71 3.17 2.3  2.72
 2.56 2.75 2.55 2.54 2.4  2.6  2.72 3.19 2.63 2.67 2.53 2.85 2.28 2.84
 2.59 2.89 2.86 2.74 2.53 2.68 2.68 2.27 2.48 2.54 2.78 2.63 2.95 2.56
 2.6  2.77 2.7  2.44 2.58 2.55 2.67 2.54 2.48 2.81 2.61 2.92 2.5  2.43
 2.78 2.49 2.58 2.51 2.98 2.49 3.12 2.72 2.83 2.25 4.31 2.6  2.66 2.45
 2.55 2.39 2.58 2.76 3.57 2.83 2.47 2.76 3.01 2.19 2.57 2.79 2.83 2.88
 2.68 2.54 2.6  2.8  2.55 2.55 2.46 2.77 2.36 2.49 2.58 2.78 2.75 2.72
 3

In [394]:
assert_equal(np.isnan(X_train).sum(),0)
assert_equal(np.isnan(X_test).sum(),0)


# Check that you get exactly the same result using your own method and sklearn's.



In [464]:
#WRITE YOUR CODE HERE
assert_equal(X_test, )
assert_equal(X_train, )

TypeError: assert_equal() missing 1 required positional argument: 'desired'

# KNN

Make now the KNN regression algorithm from scratch.

* use euclidean again 
* use `np.argsort` and `[:k]` to find the indexes of the k nearest neighbor rows
* use so called *fancy indexing* on numpy array 
    * `X_train[[2,5,3]]` gives the 2D array with the 2nd, 5th and 3rd row of `X_train`.


## Evaluate with RMSE (root mean square error)

1. Program the formula for RMSE from scratch 
2. Compute `Y_predicted`
3. Compute the RMSE for the kNN algorithm on this dataset.

## Do the same for $R^2$.

In [477]:
from scipy.spatial.distance import euclidean


def  knn(ExamplesX,ExamplesY,instance,k=5):
    kNN_Y = [ExamplesY[i] for i in np.argsort([euclidean(instance, node) for node in ExamplesX])[:k]]
    kNN_Y = mode(kNN_Y)[0][0]
    return kNN_Y.mean()


knn(X_train,Y_train,X_test[0,:]), Y_test[0]



(1832.19, array([421.09]))

In [424]:
# import math 
def rmse(u,v): ## u, v are 1D arrays of the same length
    #WRITE YOUR CODE HERE
    u,v = np.array(u), np.array(v)
    return math.sqrt(sum((u - v)**2)/ len(u))

rmse([2,3,5,6,7,34],[2,3,5,6,7,34])

0.0

In [471]:
def rsquare(predicted,true): ## u, v are 1D arrays of the same length
    #WRITE YOUR CODE HERE
    predicted,true = np.array(predicted), np.array(true)
    RSS = sum((predicted - true)**2)
    TSS = sum((predicted - np.mean(true))**2)
    return 1- (RSS / TSS)
    
rsquare([2,3,5,6,7,34],[2,3,5,6,7,34])

1.0

In [493]:
Y_predicted = knn(X_train,Y_train,X_test[0,:])
# RMSE= rmse(Y_predicted, Y_test)
print(Y_predicted)
#WRITE YOUR CODE HERE

Y_predicted.shape,RMSE 

1832.19


((), None)

# What is happening here?

* Explain what we are doing in the next cell.
* Is this according to your intuition?

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

neigh = KNeighborsRegressor(n_neighbors=5)
neigh.fit(X_train, Y_train)

Y_predicted2= neigh.predict(X_test )

rmse(Y_predicted2,Y_test)


YOUR ANSWER HERE

# Normalization


## Z- transformation

* We transform the data such that each kolom has a mean of 0 and a standard deviation of 1.

## Unit normalization

* We transform the data such that each row has unit norm.
* A unit normn of a vector $v$ means that its length equals 1, that is $\sqrt{v\cdot v}$ equals 1, where $v\cdot v$ is the dot product of $v$ with itself, that is $\Sigma_i v_i\cdot v_i$.


## Your task

* Implement both normalisations of a matrix and **make tests to check that they work correctly**.
    * Check out `np.linalg.norm?`
    * Tests are real computer tests. Not a print that you then check with your eyes.
    * So use `assert` statements, or make a test which returns True.
    * Of course you may add a useful print. 
* Do not use predefined functions for these normalisations, but program them from the here given definitions.
* Finally check that they give the same results as the [scikit learn normalizer](https://scikit-learn.org/stable/modules/preprocessing.html#normalization) and [standardizer](https://scikit-learn.org/stable/modules/preprocessing.html#standardization-or-mean-removal-and-variance-scaling).

In [526]:
# Assume M is a np.array
def standardize(M):
    #WRITE YOUR CODE HERE
    return (M - np.mean(M)) / np.std(M)
    
    
def normalize(X):
    #WRITE YOUR CODE HERE
    return (X - np.min(X)) / (np.min(X) - np.max(X))


    
X = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                   [ 0.,  1., -1.]])  

np.std(standardize(X))


normalize(X_train)


array([[-1.63347475e-06, -1.52815032e-05, -1.06396599e-05, ...,
        -0.00000000e+00, -2.17762997e-02, -4.79699188e-02],
       [-1.62086105e-06, -1.72681617e-05, -7.51146113e-06, ...,
        -0.00000000e+00, -1.86001689e-02, -7.26738594e-03],
       [-2.02449960e-06, -1.97341409e-05, -5.53110950e-06, ...,
        -5.92844119e-05, -1.70032739e-02, -8.88578732e-02],
       ...,
       [-1.84160088e-06, -1.61329283e-05, -4.72383240e-06, ...,
        -0.00000000e+00, -2.72683067e-02, -6.94069099e-03],
       [-1.87313514e-06, -1.51301387e-05, -5.81491785e-06, ...,
        -0.00000000e+00, -2.82023516e-02, -6.67391114e-03],
       [-1.65239531e-06, -1.55337773e-05, -9.54226758e-06, ...,
        -0.00000000e+00, -1.82854570e-02, -6.87699178e-03]])

Here in the answer cell below:

* your own tests
*  tests that scikit learn functions do the same


In [ ]:
#WRITE YOUR CODE HERE

In [ ]:
assert_equal(X.shape, normalize(X).shape)
assert_equal(X.shape, standardize(X).shape)


### Question 3
 
 
* Do the KNN regression again but now on the normalized data.
* Conclude.

In [ ]:
#WRITE YOUR CODE HERE

# Improving KNN

With KNN each neighbour is equal, as we take the mean or the majority class. Now, we may change KNN by *weighing* the imprtance of the neighbors, for instance with the distance or similarity. 

Implement that improvement:

* find an easy way to create weights from distances.
* normalize these weighjts so that the weights of all neighbours add up to 1.
* find out the wonderfullness of the *dot product*, see how you take the dot product of 2 numpy arrays, and, well, use it to compute the weighted mean, basically by saying *weights times values*. 

* Work it out using the tips dataset for which you predict the tip from the total bill.
* Do all steps we do in an ML project and predict the tip using KNN regression with weighted neighbors.

 

In [ ]:
tips = sns.load_dataset('tips')
print(tips.shape)
sns.regplot(x='total_bill', y='tip', data=tips);
tips.head()

# Male vs Female

We  wonder if males tip differently than females. We first investigate visually. Then we compute.

1. Add `hue='sex'` to the `sns.scatterplot` command. 
2. Simply plot two regplots on top of each other, one for the males, one for the females.
   * Of course you use Boolean indexing to restrict `data` to the required sex.
3. Read up what those shaded areas in the `regplot` mean. Can you draw a conclusion about male vs female tipping?
4. Finally run your weighted KNN and a scikit learn linear regression, and plot the regression line, the true values and the KNN-predicted tips for the test-set. Can you conclude something?

In [ ]:
#WRITE YOUR CODE HERE